# Generated by Django 5.0.3 on 2024-05-19 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='created_at',
        ),
    ]
